# Generated by Django 6.0.7 on 2026-07-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('seconds_listened', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_percentage', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('direct', 'Direct / search'), ('playlist', 'Playlist'), ('artist_page', 'Artist page'), ('album_page', 'Album page'), ('recommendation', 'Recommended'), ('other', 'Other')], default='other', max_length=20)),
                ('listener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_events', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='music.song')),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['song', 'played_at'], name='analytics_p_song_id_79ecc3_idx'), models.Index(fields=['listener', 'played_at'], name='analytics_p_listene_e24c8b_idx')],
            },
        ),
    ]
