# Generated by Django 6.0.1 on 2026-07-13 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow')], help_text='"follow" or "unfollow"', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('artist', models.ForeignKey(help_text='The artist/creator being followed or unfollowed', on_delete=django.db.models.deletion.CASCADE, related_name='follow_events_received', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(help_text='The user who performed the follow/unfollow', on_delete=django.db.models.deletion.CASCADE, related_name='follow_events_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['artist', 'timestamp'], name='analytics_artist_follow_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the play was logged')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='How many seconds of the song the user listened to')),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code of the listener', max_length=2)),
                ('song', models.ForeignKey(help_text='The song that was played', on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='music.song')),
                ('user', models.ForeignKey(blank=True, help_text='The listener (null = anonymous play)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['song', 'played_at'], name='analytics_song_played_idx'), models.Index(fields=['played_at'], name='analytics_played_at_idx'), models.Index(fields=['country_code'], name='analytics_country_idx')],
            },
        ),
    ]
