# Generated by Django 6.0.7 on 2026-07-08 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VERIFY_CREATOR', 'Verify Creator'), ('UNVERIFY_CREATOR', 'Unverify Creator'), ('SUSPEND_CREATOR', 'Suspend Creator'), ('UNSUSPEND_CREATOR', 'Unsuspend Creator'), ('DELETE_CREATOR', 'Delete Creator'), ('APPROVE_SONG', 'Approve Song'), ('REJECT_SONG', 'Reject Song'), ('DELETE_SONG', 'Delete Song'), ('DELETE_ALBUM', 'Delete Album')], max_length=100)),
                ('target_model', models.CharField(help_text="Model class name of the affected object, e.g. 'Song'.", max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the affected object at the time of the action.', null=True)),
                ('detail', models.JSONField(blank=True, default=dict, help_text="Contextual snapshot, e.g. {'title': 'Song Name', 'reason': '...'}.")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='Staff user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
